language: java
sudo: required
before_install: 
- cat /etc/hosts # optionally check the content *before*
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
- cat /etc/hosts # optionally check the content *after*
- ant init-ivy
script: ant all
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: BbFdY+H/HadvKB15SOnjnfYLGlbqSaW0tHlYW5hjtBUoQFpOVe57IneVwIi8tom/LSADYKjyFuja8KabVSzHoCbXRevbCgFI84rfb8bLejuoCauIJE/Zwah5b4a3IgW04Q+xxgNPeozS/Dol+IC+C3Xlnb5IXe+VNodTfY3ZmDA=
  file: dist/go-generic-artifactory-poller.jar
  skip_cleanup: true
  on:
    repo: varchev/go-generic-artifactory-poller
    tags: true
    all_branches: true
